### ISSUE TITLE
Team Charter

### ISSUE THREAD

**Issue by CallumChalmers29** [Adamthe1st/Green-cortex#1]
Great Team Charter Ahmed! I love how simple and clear you have made it, you have really grasped the concept of making a short but powerful overarching document for the running of the project. Just a few comments:

Project Vision: I think this is more your personal vision rather than the vision for the project - maybe put in some more specific details about your project e.g. what specific area your project is on and what problem your project is aiming to solve

Mission: This is good, you could add what medium you are using to make the software i.e. Python, R etc.

Success criteria: I like how you kept it simple but still managed to cover a broad range of criteria, the second bullet is maybe a little ambiguous, you could specify what you consider 'gaining a skill'

Behavioural Agreement: Excellent – great principles for a team to strive for

Communication Agreement: Very clear, I like how there is no overlap between the behavioural principles and the communication principles and it is clear exactly what method of communication should be used for the different types of communication

Team members: Would be good to define what roles each person will play in team  

Keep up the good work, stay Agile and I'm sure your project will run smoothly :)

**Comment by Adamthe1st** [comment]
Thanks Callum for your valuable feedback in my team charter! Your highlights will be taken into consideration :+1:

**Comment by CallumChalmers29** [comment]
Sorry Ahmed, just saw this now. Regarding the vision, I see it as the reason for why you are doing the project/the aim of the project whereas the mission is more along the lines of how you are going to accomplish it. So for your project the vision would be something along the lines of "To use machine learning to help with the classification of databases" (I don't fully understand how machine learning works so that specific description may be wrong, you will have a better understanding of the precise aim of your project) With regards to the changes, they look good, you could add comments to all your commits just giving a brief description of what each one means just so people can understand what you changed and the rationale for any changes :)

**Comment by CallumChalmers29** [comment]
Hi @Adamthe1st, just looking for your DMP so we can have the final sign off, where is it?

Thanks
Callum

**Comment by Adamthe1st** [comment]
Dear @CallumChalmers29, 

I have updated my TC adhering to your valuable comments and made a pull request to the class repo. in the meantime, please feel free to review my updated team charter in the link below and close the issue when you wish. 

Cheers 
Ahmed

**Comment by CallumChalmers29** [comment]
Looking great, much better project vision! I am happy to close the issue now :)
