### ISSUE TITLE
Data Management Plan

### ISSUE THREAD

**Issue by CallumChalmers29** [Adamthe1st/Green-cortex#2]
Could you upload your Data Management Plan to this repo so i can give you feedback? :)

**Comment by CallumChalmers29** [comment]
Hi Ahmed,

I read your data management plan in your other repo, great start so far! Just a few small comments:

- **How will the data be collected?** You mention that Python will be used for data collection but in reality I think you mean that data will be collected from your supervisor, Python is just being used to manipulate the data you have collected to make it more meaningful. This DMP template is more tailored towards people who are generating their own data and so not all the fields are necessarily relevant to you project so keep that in mind :)

-**How will the data be stored and backed up?** You provide the locations which is a great start but I think you need more detail on why you need two locations, what will be different between the two locations and how you will manage moving between the two locations.

-**Access and security** You said you needed help with this section so I'll give you my two cents. The data is from 2002-2004 and is not going to change so I think it is reasonable that only you need access to the data during the project and so security can be managed by simply keeping the data on your computer with a password. You supervisor should have the original data anyway in the unlikely event they need to use it and so access need not be shared. You also mention later on that the data will be uploaded to Github which I don't think is necessary and essentially makes the data public which may not be what your supervisor wants.

-You also mentioned you needed help with Retention and Disposal, Licensing, Publishing and Long term management - my advice would be to talk to your supervisor as the data belongs to them and so all of this definitely needs to managed with their wishes in mind. That being said we will be learning about this stuff soon so maybe wait until we have had the lectures so you can ask meaningful questions. 

-**Who will manage the data?** You said you needed help with this, it is my understanding part of the course is us managing the data and learning the difficulties around this so the simple answer is YOU.

Another quick tip is, once you have finished with a field you can delete all the stuff in square brackets to make it look cleaner but that is just formatting. 

You have definitely got a solid foundation, once you make some progress on your project and talk to your supervisor so you can fill in the remaining boxes I will give you feedback on the rest :) Keep up the good work!

**Comment by CallumChalmers29** [comment]
Hi @Adamthe1st just wondering if you made these changes so we can close this issue?

Thanks
Callum

**Comment by Adamthe1st** [comment]
Hello call. I am making the changes. Will upload DMP by 3 pm. Ill slack you
once it has been uploaded. Sorry for the lateness

Ahmed

**Comment by Adamthe1st** [comment]
Dear Callum,

Thank you so much for your great feedback! I have now updated my DMP as per
your suggestions. I have also made a pull request. However in the meantime,
feel free to review the DMP here:
https://github.com/Adamthe1st/Adamthe1st-green-cortex

or just open the attached file :)

once you are pleased with the changes, please feel free to let me know so
that we could have a final handshake.

Cheers
Ahmed

**Comment by CallumChalmers29** [comment]
Great work Ahmed! All my feedback was addressed and your DMP is looking great - just a few more fields to fill out - you're nearly there! :) I'm happy to close this issue
